-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 11:37:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

--To execute this file, run mysql -u root < schema.sql in command line

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fant4syFootball
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fant4syFootball
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fant4syFootball` DEFAULT CHARACTER SET utf8 ;
USE `fant4syFootball` ;

-- -----------------------------------------------------
-- Table `fant4syFootball`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fant4syFootball`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fant4syFootball`.`leagues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fant4syFootball`.`leagues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fant4syFootball`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fant4syFootball`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `owner` INT NOT NULL,
  `league` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`name` ASC),
  INDEX `user_idx` (`owner` ASC),
  INDEX `league_idx` (`league` ASC),
  CONSTRAINT `owner`
    FOREIGN KEY (`owner`)
    REFERENCES `fant4syFootball`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `league`
    FOREIGN KEY (`league`)
    REFERENCES `fant4syFootball`.`leagues` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fant4syFootball`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fant4syFootball`.`players` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `position` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fant4syFootball`.`Teams_has_Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fant4syFootball`.`Teams_has_Players` (
  `Teams_id` INT NOT NULL,
  `Players_id` INT NOT NULL,
  PRIMARY KEY (`Teams_id`, `Players_id`),
  INDEX `fk_Teams_has_Players_Players1_idx` (`Players_id` ASC),
  INDEX `fk_Teams_has_Players_Teams_idx` (`Teams_id` ASC),
  CONSTRAINT `fk_Teams_has_Players_Teams`
    FOREIGN KEY (`Teams_id`)
    REFERENCES `fant4syFootball`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teams_has_Players_Players1`
    FOREIGN KEY (`Players_id`)
    REFERENCES `fant4syFootball`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fant4syFootball`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fant4syFootball`.`matches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team1_id` INT NOT NULL,
  `team2_id` INT NOT NULL,
  `week` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `team1_id_idx` (`team1_id` ASC),
  INDEX `team2_id_idx` (`team2_id` ASC),
  CONSTRAINT `team1_id`
    FOREIGN KEY (`team1_id`)
    REFERENCES `fant4syFootball`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `team2_id`
    FOREIGN KEY (`team2_id`)
    REFERENCES `fant4syFootball`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fant4syFootball`.`playerStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fant4syFootball`.`playerStats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `playerId` INT NOT NULL,
  `week` INT NOT NULL,
  `passingYards` INT NULL default 0,
  `passingTouchdowns` INT NULL default 0,
  `passingInterceptions` INT NULL default 0,
  `rushingYards` INT NULL default 0,
  `rushingTouchdowns` INT NULL default 0,
  `receptions` INT NULL default 0,
  `receivingYards` INT NULL default 0,
  `receivingTouchdowns` INT NULL default 0,
  `fumbles` INT NULL default 0,
  `fieldGoalsMade0to19` INT NULL default 0,
  `fieldGoalsMade20to29` INT NULL default 0,
  `fieldGoalsMade30to39` INT NULL default 0,
  `fieldGoalsMade40to49` INT NULL default 0,
  `fieldGoalsMade50Plus` INT NULL default 0,
  `extraPointsMade` INT NULL default 0,
  `twoPointCoversionPasses` INT NULL default 0,
  `twoPointCoversionRuns` INT NULL default 0,
  `twoPointCoversionReceptions` INT NULL default 0,
  `isGameOver` TINYINT NULL default 1,
  PRIMARY KEY (`id`),
  INDEX `playerId_idx` (`playerId` ASC),
  CONSTRAINT `playerId`
    FOREIGN KEY (`playerId`)
    REFERENCES `fant4syFootball`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;